
# deepcgh_fixed.py

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import warnings
from skimage.draw import disk, line_aa
import numpy as np
from tqdm import tqdm
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, MaxPooling2D, UpSampling2D, Concatenate, Lambda
from scipy.ndimage import gaussian_filter

### MODIFIED: 导入用于生成结构化文本图案的函数 ###
from utils import make_text_gaussian_dotlattice_volume

try:
    from tensorflow.keras import mixed_precision
    mixed_precision.set_global_policy('float32')
except Exception:
    pass
tf.config.optimizer.set_jit(False)

class DeepCGH_Datasets(object):
    def __init__(self, params):
        try:
            self.path = params.get('data_path', 'dd/Disks')
            self.shape = params['shape']
            self.N = params['N']
            self.ratio = params['train_ratio']
            self.object_size = params.get('object_size', [3, 10])
            self.intensity = params.get('intensity', [0.6, 1.0])
            self.object_count = params.get('object_count', [10, 30])
            self.name = params['name']
            # object_type is now used as a default/fallback, but generation is randomized
            self.object_type = params.get('object_type', 'Disk') 
            self.centralized = params.get('centralized', False)
            self.normalize = params.get('normalize', True)
            self.compression = params.get('compression', 'GZIP')
        except KeyError as e:
            assert False, f'Missing parameter: {e}'
        os.makedirs(self.path, exist_ok=True)
        self.__check_avalability()
        print(f'[DATA] writing TFRecords to: {self.path}')
    
    def __check_avalability(self):
        self.filename = f"{self.name}_SHP{self.shape}_N{self.N}_Split.tfrecords" # Use name for uniqueness
        self.absolute_file_path = os.path.join(os.getcwd(), self.path, self.filename)
        if not (os.path.exists(self.absolute_file_path.replace('Split', '')) or 
                os.path.exists(self.absolute_file_path.replace('Split', 'Train'))):
            warnings.warn('Dataset files not found. They will be generated by getDataset().')
        else:
            print('Dataset already exists.')
    
    def __get_line(self, shape, start, end):
        img = np.zeros(shape, dtype=np.float32)
        rr, cc, val = line_aa(start[0], start[1], end[0], end[1])
        img[rr, cc] = val * 1
        return img
    
    def get_circle(self, shape, radius, location):
        if isinstance(radius, (list, tuple)) and len(radius) == 2:
            sigma = np.random.randint(radius[0], radius[1] + 1)
        else:
            sigma = radius
        y = np.arange(0, shape[0], 1, dtype=np.float32)
        x = np.arange(0, shape[1], 1, dtype=np.float32)
        xx, yy = np.meshgrid(x, y)
        dist_sq = (xx - location[1])**2 + (yy - location[0])**2
        gaussian = np.exp(-dist_sq / (2 * sigma**2))
        img = gaussian.astype(np.float32)
        forbid_radius = int(np.ceil(2 * sigma))
        rr_forbid, cc_forbid = disk((location[0], location[1]), forbid_radius, shape=img.shape)
        return img, rr_forbid, cc_forbid
    
    def __get_allowables(self, allow_x, allow_y, forbid_x, forbid_y):
        allow_x.difference_update(forbid_x)
        allow_y.difference_update(forbid_y)
        return allow_x, allow_y
    
    def __get_randomCenter(self, allow_x, allow_y):
        list_x = list(allow_x)
        list_y = list(allow_y)
        ind_x = np.random.randint(0, len(list_x))
        ind_y = np.random.randint(0, len(list_y))
        return list_x[ind_x], list_y[ind_y]
    
    def __get_randomStartEnd(self, shape):
        start = (np.random.randint(0, shape[0]), np.random.randint(0, shape[1]))
        end = (np.random.randint(0, shape[0]), np.random.randint(0, shape[1]))
        return start, end
    
    def __get_RandDots(self, shape, maxnum = [10, 20]):
        n = np.random.randint(int(maxnum[0]), int(maxnum[1]) + 1)
        image = np.zeros(shape)
        if n > 0:
            xs = np.random.randint(0, shape[0], (n,))
            ys = np.random.randint(0, shape[1], (n,))
            image[xs, ys] = 1
        return image

    def __get_RandLines(self, shape, maxnum = [10, 20]):
        n = np.random.randint(int(maxnum[0]), int(maxnum[1]) + 1)
        image = np.zeros(shape)
        for i in range(n):
            start, end = self.__get_randomStartEnd(shape)
            img = self.__get_line(shape, start, end)
            image += img
        if image.max() > 1e-9:
            image -= image.min()
            image /= image.max()
        return image
    
    def __get_RandBlobs(self, shape, maxnum = [10,12], radius = 5, intensity = 1):
        n = np.random.randint(int(maxnum[0]), int(maxnum[1]) + 1)
        image = np.zeros(shape)
        try:
            r = radius[-1]
        except TypeError:
            r = radius
        allow_x = set(range(shape[0]))
        allow_y = set(range(shape[1]))
        if not self.centralized:
            forbid_x = set(list(range(r)) + list(range(shape[0]-r, shape[0])))
            forbid_y = set(list(range(r)) + list(range(shape[1]-r, shape[1])))
        else:
            forbid_x = set(list(range(r)) + list(range(shape[0]-r, shape[0])) + list(range(shape[0]//6, (5)*shape[0]//6)))
            forbid_y = set(list(range(r)) + list(range(shape[1]-r, shape[1])) + list(range(shape[1]//6, (5)*shape[1]//6)))
        allow_x, allow_y = self.__get_allowables(allow_x, allow_y, forbid_x, forbid_y)
        for i in range(n):
            if not allow_x or not allow_y:
                break
            x, y = self.__get_randomCenter(allow_x, allow_y)
            r_val = np.random.randint(radius[0], radius[1]+1) if isinstance(radius, (list, tuple)) else radius
            int_4_this = np.random.uniform(intensity[0], intensity[1]) if isinstance(intensity, list) else intensity
            img, xs, ys = self.get_circle(shape, r_val, (x,y))
            allow_x, allow_y = self.__get_allowables(allow_x, allow_y, set(xs), set(ys))
            image += img * int_4_this
        return image

    ### NEW: Function to generate structured text patterns ###
    def __get_RandText(self, shape):
        H, W, C = shape
        # Character pool for training
        chars = ['A','B','C','G','H','S','T','U','X','I','1','2','3','4','5','6','7']
        random_texts = np.random.choice(chars, C).tolist()

        # Use randomized parameters to create diverse samples
        return make_text_gaussian_dotlattice_volume(
            H, W, C,
            texts=random_texts,
            dot_sigma=np.random.uniform(1.8, 2.8),
            grid_step=np.random.randint(20, 30),
            accept_radius=np.random.randint(8, 12),
            letter_height_ratio=np.random.uniform(0.5, 0.7),
            bold=np.random.randint(0, 2)
        )
    
    ### MODIFIED: Generate a mix of different pattern types ###
    def get_randSample(self):
        # Define the types of patterns to generate and their probabilities
        available_types = ['Disk', 'Line', 'RandomNoise', 'StructuredText']
        # Give structured text a higher probability to ensure the model learns it well
        probabilities = [0.25, 0.15, 0.20, 0.40] 
        
        chosen_type = np.random.choice(available_types, p=probabilities)

        # StructuredText generates a full volume, so handle it separately
        if chosen_type == 'StructuredText':
            sample = self.__get_RandText(self.shape)
            # Normalization is handled inside the generation function
            return sample

        # For other types, generate plane by plane
        sample = np.zeros(self.shape, dtype=np.float32)
        for plane in range(self.shape[-1]):
            if chosen_type == 'Disk':
                img = self.__get_RandBlobs(shape=(self.shape[0], self.shape[1]),
                                           maxnum=self.object_count,
                                           radius=self.object_size,
                                           intensity=self.intensity)
            elif chosen_type == 'Line':
                img = self.__get_RandLines((self.shape[0], self.shape[1]),
                                           maxnum=self.object_count)
            elif chosen_type == 'RandomNoise':
                noise = np.random.rand(self.shape[0], self.shape[1])
                sigma = np.random.uniform(1.0, 5.0)
                img = gaussian_filter(noise, sigma=sigma)
            else: # Fallback
                img = np.zeros((self.shape[0], self.shape[1]))

            sample[:, :, plane] = img
        
        if sample.max() > 1e-9:
            sample -= sample.min()
            sample /= sample.max()
        return sample

    def __bytes_feature(self, value):
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
    
    def __generate(self):
        train_size = int(np.floor(self.ratio * self.N))
        options = tf.io.TFRecordOptions(compression_type=self.compression)
        path_train = self.absolute_file_path.replace('Split', 'Train')
        path_test = self.absolute_file_path.replace('Split', 'Test')
        with tf.io.TFRecordWriter(path_train, options=options) as writer_train:
            with tf.io.TFRecordWriter(path_test, options=options) as writer_test:
                for i in tqdm(range(self.N), desc="Generating Mixed Dataset"):
                    sample = self.get_randSample()
                    image_raw = sample.astype(np.float32).tobytes()
                    feature = {'sample': self.__bytes_feature(image_raw)}
                    features = tf.train.Features(feature=feature)
                    example = tf.train.Example(features=features)
                    example_to_string = example.SerializeToString()
                    if i < train_size:
                        writer_train.write(example_to_string)
                    else:
                        writer_test.write(example_to_string)
    
    def getDataset(self):
        train_file = self.absolute_file_path.replace('Split', 'Train')
        test_file = self.absolute_file_path.replace('Split', 'Test')
        if not (os.path.exists(train_file) and os.path.exists(test_file)):
            print('Generating data...')
            folder = os.path.dirname(self.absolute_file_path)
            if not os.path.exists(folder):
                os.makedirs(folder)
            self.__generate()
        self.dataset_paths = [train_file, test_file]

class DeepCGH(object):
    # ... The rest of the DeepCGH class remains unchanged ...
    # (No modifications are needed for the model architecture or training loop logic)
    def __init__(self, data_params, model_params):
        self.path = model_params.get('model_path', model_params.get('path', 'DeepCGH_Models'))
        self.shape = data_params['shape']
        self.plane_distance = model_params['plane_distance']
        self.quantization = 2**model_params['quantization']
        self.n_kernels = model_params['n_kernels']
        self.IF = model_params['int_factor']
        self.wavelength = model_params['wavelength']
        self.ps = model_params['pixel_size']
        self.f = model_params['focal_point']
        self.object_type = data_params.get('object_type', 'Mixed') # Default to Mixed
        self.centralized = data_params.get('centralized', False)
        self.token = model_params['token']
        self.lr = model_params['lr']
        self.batch_size = model_params['batch_size']
        self.shuffle = model_params['shuffle']
        num_planes_half = (self.shape[-1] - 1) // 2
        zs_neg = [-self.plane_distance * i for i in range(num_planes_half, 0, -1)]
        zs_pos = [self.plane_distance * i for i in range(1, num_planes_half + 1)]
        self.zs = zs_neg + [1e-6] + zs_pos
        self.__check_availability()
        m = self.shape[0]
        self.ps_img = (self.f * self.wavelength) / (self.ps * m)
        self.Hs = self.__get_H(self.zs, self.shape, self.wavelength, self.ps_img)
        self.Hs_tf = [tf.constant(H, dtype=tf.complex64) for H in self.Hs]
        self.model = self.__build_unet()
        self.optimizer = tf.keras.optimizers.Adam(learning_rate=self.lr, epsilon=1e-7, clipnorm=1.0)
        self.checkpoint = tf.train.Checkpoint(optimizer=self.optimizer, model=self.model)
        self.checkpoint_manager = tf.train.CheckpointManager(self.checkpoint, self.absolute_file_path, max_to_keep=1)
        if self.checkpoint_manager.latest_checkpoint:
            print(f"Restored from {self.checkpoint_manager.latest_checkpoint}")
            self.checkpoint.restore(self.checkpoint_manager.latest_checkpoint).expect_partial()
        else:
            print("Initializing from scratch.")
        self.loss_weights = model_params.get('loss_weights', {'cosine':0.3,'supp':0.8,'depth_ce':0.5,'xcorr':0.3,'excl':0.2})
        self.ct_params = model_params.get('ct_params', {'mask_tau':0.1, 'bg_tau':1e-3, 'temp':0.5})

    def __get_H(self, zs, shape, lambda_, dxy):
        Hs = []
        fx = np.fft.fftfreq(shape[1], d=dxy)
        fy = np.fft.fftfreq(shape[0], d=dxy)
        f_xx, f_yy = np.meshgrid(fx, fy)
        for z in zs:
            if z == 0: H = np.ones(shape[:2], dtype=np.complex64)
            else: H = np.exp(-1j * np.pi * lambda_ * z * (f_xx**2 + f_yy**2)).astype(np.complex64)
            Hs.append(np.fft.fftshift(H))
        return Hs

    def __check_availability(self):
        self.filename = 'Model_Disk_SHP{}_IF{}_Dst{}_WL{}_PS{}_F{}_{}'.format(
        self.shape, self.IF, self.plane_distance,
        self.wavelength, self.ps, self.f, self.token) # Simplified filename
        self.absolute_file_path = os.path.join(os.getcwd(), self.path, self.filename)
        print(f'Model checkpoints will be stored in:\n {self.absolute_file_path}')
        if not os.path.exists(self.absolute_file_path):
            os.makedirs(self.absolute_file_path)

    def load_data(self, path, batch_size, shuffle_buffer):
        image_feature_description = {'sample': tf.io.FixedLenFeature([], tf.string)}
        def _parse_image_function(example_proto):
            parsed = tf.io.parse_single_example(example_proto, image_feature_description)
            img = tf.reshape(tf.io.decode_raw(parsed['sample'], tf.float32), self.shape)
            return tf.cast(img, tf.float32)
        opts = tf.data.Options()
        opts.experimental_deterministic = False
        train_ds = (tf.data.TFRecordDataset(path[0], compression_type='GZIP', num_parallel_reads=tf.data.AUTOTUNE)
                    .with_options(opts).map(_parse_image_function, num_parallel_calls=tf.data.AUTOTUNE)
                    .shuffle(min(shuffle_buffer, 4 * batch_size)).batch(batch_size, drop_remainder=True).prefetch(tf.data.AUTOTUNE))
        validation_ds = (tf.data.TFRecordDataset(path[1], compression_type='GZIP', num_parallel_reads=tf.data.AUTOTUNE)
                         .with_options(opts).map(_parse_image_function, num_parallel_calls=tf.data.AUTOTUNE)
                         .batch(batch_size).prefetch(tf.data.AUTOTUNE))
        return train_ds, validation_ds

    @tf.custom_gradient
    def _quantize(self, x):
        quantized = tf.math.round((x + np.pi) * (self.quantization-1) / (2*np.pi))
        quantized = quantized / (self.quantization-1) * 2*np.pi - np.pi
        def grad(dy): return dy
        return quantized, grad
    
    def _ifft_AmPh(self, x):
        amp, phase = x[0], x[1]
        amp32, phase32 = tf.cast(tf.squeeze(amp, -1), tf.float32), tf.cast(tf.squeeze(phase, -1), tf.float32)
        img = tf.complex(amp32, 0.0) * tf.math.exp(tf.complex(0.0, phase32))
        img_sh = tf.signal.ifftshift(img, axes=[1, 2])
        slm_ = tf.signal.ifft2d(img_sh)
        modulation = tf.math.angle(slm_)
        out = self._quantize(modulation)[:, :, :, tf.newaxis]
        return tf.cast(out, amp.dtype)

    def __build_unet(self):
        def _cbn(ten, n_k, act):
            x = Conv2D(n_k, (3,3), activation=act, padding='same')(ten)
            x = BatchNormalization()(x)
            x = Conv2D(n_k, (3,3), activation=act, padding='same')(x)
            x = BatchNormalization()(x)
            return x
        def _cc(ten, n_k, act):
            x = Conv2D(n_k, (3,3), activation=act, padding='same')(ten)
            x = Conv2D(n_k, (3,3), activation=act, padding='same')(x)
            return x
        def _interleave(x): return tf.nn.space_to_depth(x, self.IF)
        def _deinterleave(x): return tf.nn.depth_to_space(x, self.IF)
        n_k = self.n_kernels
        inp = Input(shape=self.shape, name='target')
        act = 'relu'
        x1_1 = Lambda(_interleave, name='Interleave')(inp)
        x1 = _cbn(x1_1, n_k[0], act)
        x2 = MaxPooling2D((2,2), padding='same')(x1)
        x2 = _cbn(x2, n_k[1], act)
        enc = MaxPooling2D((2,2), padding='same')(x2)
        enc = _cc(enc, n_k[2], act)
        x3 = UpSampling2D(2)(enc)
        x3 = Concatenate()([x3, x2])
        x3 = _cc(x3, n_k[1], act)
        x4 = UpSampling2D(2)(x3)
        x4 = Concatenate()([x4, x1])
        x4 = _cc(x4, n_k[0], act)
        x4 = _cc(x4, n_k[1], act)
        x4 = Concatenate()([x4, x1_1])
        phi_0_ = Conv2D(self.IF**2, (3,3), activation=None, padding='same')(x4)
        phi_0 = Lambda(_deinterleave, name='phi_0')(phi_0_)
        amp_0_ = Conv2D(self.IF**2, (3,3), activation='sigmoid', padding='same')(x4)
        amp_0 = Lambda(_deinterleave, name='amp_0')(amp_0_)
        phi_slm = Lambda(self._ifft_AmPh, name='phi_slm')([amp_0, phi_0])
        return Model(inputs=inp, outputs=phi_slm)

    def _forward_U0_spectrum(self, phi_slm):
        phase32 = tf.cast(tf.squeeze(phi_slm, -1), tf.float32)
        cf_slm = tf.math.exp(tf.complex(0.0, phase32))
        H, W = tf.cast(self.shape[0], tf.float32), tf.cast(self.shape[1], tf.float32)
        norm_factor = tf.sqrt(H * W)
        u0 = tf.signal.fftshift(tf.signal.fft2d(tf.signal.fftshift(cf_slm, [1,2])), [1,2]) / tf.complex(norm_factor, 0.0)
        U0 = tf.signal.fftshift(tf.signal.fft2d(tf.signal.fftshift(u0, [1,2])), [1,2]) / tf.complex(norm_factor, 0.0)
        return U0
        
    @tf.function
    def _loss_streaming(self, targets, U0_spectrum):
        B, H, W, C = tf.shape(targets)[0], tf.shape(targets)[1], tf.shape(targets)[2], tf.shape(targets)[3]
        norm_factor = (self.ps_img / self.wavelength) ** 2
        epsilon = 1e-8
        pred_planes = []
        for p in range(len(self.Hs_tf)):
            Uz = U0_spectrum * self.Hs_tf[p]
            uz = tf.signal.ifftshift(tf.signal.ifft2d(tf.signal.ifftshift(Uz, [1,2])), [1,2]) * tf.complex(norm_factor, 0.0)
            pred_I = tf.square(tf.abs(uz))
            pred_planes.append(pred_I)
        pred_stack = tf.stack(pred_planes, axis=-1)
        true_flat = tf.reshape(tf.cast(targets, tf.float32), [B, -1])
        pred_flat = tf.reshape(pred_stack, [B, -1])
        dot = tf.reduce_sum(true_flat * pred_flat, 1)
        true_norm = tf.sqrt(tf.reduce_sum(tf.square(true_flat), 1) + epsilon)
        pred_norm = tf.sqrt(tf.reduce_sum(tf.square(pred_flat), 1) + epsilon)
        ac = dot / (true_norm * pred_norm + epsilon)
        return tf.reduce_mean(1.0 - ac)
        
    @tf.function
    def _train_step(self, inputs, targets):
        with tf.GradientTape() as tape:
            phi_slm = self.model(inputs, training=True)
            U0_spectrum = self._forward_U0_spectrum(phi_slm)
            loss = self._loss_streaming(targets, U0_spectrum)
        vars = self.model.trainable_variables
        grads = tape.gradient(loss, vars)
        self.optimizer.apply_gradients(zip(grads, vars))
        return loss

    @tf.function
    def _val_step(self, inputs):
        phi_slm = self.model(inputs, training=False)
        U0_spectrum = self._forward_U0_spectrum(phi_slm)
        return self._loss_streaming(inputs, U0_spectrum)
        
    def train(self, deepcgh_dataset, epochs):
        train_ds, validation_ds = self.load_data(deepcgh_dataset.dataset_paths, self.batch_size, self.shuffle)
        best_val_loss = float('inf')
        train_loss_history, val_loss_history = [], []
        for epoch in range(epochs):
            print(f"\nEpoch {epoch + 1}/{epochs}")
            prog_bar = tf.keras.utils.Progbar(target=None, stateful_metrics=['val_loss'])
            epoch_train_losses = []
            for i, inputs in enumerate(train_ds):
                loss = self._train_step(inputs, inputs)
                epoch_train_losses.append(loss.numpy())
                prog_bar.update(i + 1, [("loss", loss)])
            val_losses = []
            for inputs in validation_ds:
                val_loss = self._val_step(inputs)
                val_losses.append(val_loss.numpy())
            mean_train_loss = np.mean(epoch_train_losses)
            mean_val_loss = np.mean(val_losses)
            train_loss_history.append(mean_train_loss)
            val_loss_history.append(mean_val_loss)
            prog_bar.update(i + 1, [("loss", mean_train_loss), ("val_loss", mean_val_loss)])
            if mean_val_loss < best_val_loss:
                best_val_loss = mean_val_loss
                save_path = self.checkpoint_manager.save()
                print(f"  New best model found with val_loss: {best_val_loss:.6f}. Saved checkpoint to {save_path}")
            else:
                print(f"  Validation loss ({mean_val_loss:.6f}) did not improve from best ({best_val_loss:.6f}).")
        return train_loss_history, val_loss_history

    def get_hologram(self, inputs):
        inputs_tensor = tf.convert_to_tensor(inputs, dtype=tf.float32)
        predictions = self.model(inputs_tensor, training=False)
        return predictions.numpy()